### ISSUE TITLE
Where is the preprocess.py noted  in README.md

### ISSUE THREAD

**Issue by zhiqiuyuan** [eddiegaoo/SIMPLE#1]
I read the README.md and notice the instruction:
```bash
python preprocess.py --data \<NameOfDataset> --txt \<PathOfRawData>
```
But I can't find where is the `preprocess.py`

**Comment by eddiegaoo** [comment]
Hi, 

The preprocess.py file has been uploaded.

**Comment by zhiqiuyuan** [comment]
> Hi,
> 
> The preprocess.py file has been uploaded.

Thanks!
