### ISSUE TITLE
Main.py Execution Failure Due to Undefined Function and Incorrect Function Calls in funciton eval()

### ISSUE THREAD

**Issue by griii** [eddiegaoo/SIMPLE#2]
Hello,

I am encountering an issue with the execution of the main.py file in this project. Specifically, the eval function within the file is attempting to call the prepare_input_eval function, which is not defined anywhere in the project. This is causing the file to fail when executed.

In addition to this, there are some other functions in the main file that end with "_eval" and have some abnormalities. I hope the author can provide a version that can run successfully.

For reference, here is a snippet of the problematic code in the eval function:
![图片](https://github.com/eddiegaoo/SIMPLE/assets/62171786/78f524e9-449d-4ce0-b63c-dff93b1edae1)

**Comment by eddiegaoo** [comment]
> Hello,
> 
> I am encountering an issue with the execution of the main.py file in this project. Specifically, the eval function within the file is attempting to call the prepare_input_eval function, which is not defined anywhere in the project. This is causing the file to fail when executed.
> 
> In addition to this, there are some other functions in the main file that end with "_eval" and have some abnormalities. I hope the author can provide a version that can run successfully.
> 
> For reference, here is a snippet of the problematic code in the eval function: ![图片](https://private-user-images.githubusercontent.com/62171786/341251820-78f524e9-449d-4ce0-b63c-dff93b1edae1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NjkyNjEsIm5iZiI6MTcxODg2ODk2MSwicGF0aCI6Ii82MjE3MTc4Ni8zNDEyNTE4MjAtNzhmNTI0ZTktNDQ5ZC00Y2UwLWI2M2MtZGZmOTNiMWVkYWUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA3MzYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhMjEzYThmYWNiMjU5MDgzNDY1MDZjY2VhYzAzZmYzYjA2ZTA2ZGI3ZTRiN2M1MjZlYTM0ZjljMDMwNTQ0M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RNfTtsZCKJGGIIrFV6F5gOZze3zW94fvpVhmKl7lQo8)

Hi, thanks for your interest in this project.

It seems there is a problem with the code version. I'll check it and get back to you soon.

**Comment by eddiegaoo** [comment]
> Hello,
> 
> I am encountering an issue with the execution of the main.py file in this project. Specifically, the eval function within the file is attempting to call the prepare_input_eval function, which is not defined anywhere in the project. This is causing the file to fail when executed.
> 
> In addition to this, there are some other functions in the main file that end with "_eval" and have some abnormalities. I hope the author can provide a version that can run successfully.
> 
> For reference, here is a snippet of the problematic code in the eval function: ![图片](https://private-user-images.githubusercontent.com/62171786/341251820-78f524e9-449d-4ce0-b63c-dff93b1edae1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NzA2NDgsIm5iZiI6MTcxODg3MDM0OCwicGF0aCI6Ii82MjE3MTc4Ni8zNDEyNTE4MjAtNzhmNTI0ZTktNDQ5ZC00Y2UwLWI2M2MtZGZmOTNiMWVkYWUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA3NTkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2ZTk3MTg2YmQyNTBlNmVhMTIxOTU4ZjU0ZjVjMDcxODI5OGY3M2VmZDE5MzJmODg4MjVkZjI5MjEzMTJiZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-dcw77UznPcMbLXKyWXZyB9P_1gPOVtOSYI1Af41Xi8)

The bug has been fixed. The prepare_input_eval() is now defined in data_processing.py under the folder named SIMPLE.

It should work fine now. Also, if you would like to test solely about the training efficiency, you can neutralize the evaluation part of the code.

**Comment by griii** [comment]
Thank you very much, I have successfully run it.
